### ISSUE TITLE
Config value for default in the future

### ISSUE THREAD

**Issue by rubdos** [dfhoughton/two-timer#3]
Hi!

I've used this library for a Matrix bot to set reminders. We currently type "18:00 today", because "18:00" is in the past (it assumes yesterday). Is it possible to somehow add a field to `Config`, to configure `two_timer` to assume times lie in the future, instead of in the past?

Thanks!

Ruben

**Comment by dfhoughton** [comment]
It's been a little while since I looked at the code, but I think this would be simple. I'll see if I can get to this this weekend.

**Comment by dfhoughton** [comment]
@rubdos , I just published a new version with this field added to the config struct. Previously relative time expressions were assumed to be past relative to the present. Now they are configurable. `Config::new().default_to_past(false)` will give you a configuration that will interpret "18:00" as the 18:00 after now rather than the 18:00 before. Here's the commit: 8354b38700673fc2f7bbd6e66f950d1ba85e424a. You can see the tests I added for this. These could be a lot more extensive.

**Comment by dfhoughton** [comment]
I'll assume this is working until I learn otherwise.

**Comment by rubdos** [comment]
Thanks! I didn't see this in my flood of Github notifications!

**Comment by dfhoughton** [comment]
No problem.
